### ISSUE TITLE
Migration AAA

### ISSUE THREAD

**Issue by Olivia206** [noesya/communicationdemocratie-site#10]
### Choix site / thème

- [ ] Block posts layout list : faut-il aligner le texte malgré l'absence d'image : https://www.communication-democratie.org/fr/enjeux/influence-politique/ / http://localhost:1313/fr/enjeux/influence-politique/

**Comment by alexisben** [comment]
Post single : 

- Ajout de l'auteur et de sa description dans le block chapo 
- Dissocier le post-sidebar en 2 parties (post-infos et toc)
- Déplacer la toc sous le chapo


![image](https://user-images.githubusercontent.com/4630530/210065483-6cbd4768-75ea-4397-8b49-ca52b4f0cd85.png)
