### ISSUE TITLE
Recette

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/communicationdemocratie-site#12]
https://aaa--communication-democratie.netlify.app/fr/plaidoyers/campagne-pour-une-loi-evin-du-climat-europeenne/
- [x] Enlever le bold du CTA

https://aaa--communication-democratie.netlify.app/fr/publications/2022-04-14-decret-neutralite-carbone-de-la-transparence-mais-pas-de-regulation-contre-le-greenwashing/
- [x] Enlever le bloc de partage

**Comment by alexisben** [comment]
On est sûr pour le bold du CTA ?


<img width="999" alt="image" src="https://user-images.githubusercontent.com/4630530/214510922-418cd04b-af27-4df6-85d4-201bfbe20515.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/4630530/214510988-d74d4daa-1f22-4f99-88d7-16bd14aebb5c.png">
