### ISSUE TITLE
Retours

### ISSUE THREAD

**Issue by sebousan** [noesya/communicationdemocratie-site#2]
- [x] Agrandir title first post sur la home
- [x] Réduire la taille de l'image dans un item  plaidoyer
- [x] Bonne couleur du picto dans un item plaidoyer
- [x] Aside si page sans enfant
- [x] Merge to master
- [ ] Couleur des liens, partout
- [ ] Bien avoir une opacity (.3) pour le souligné partout

**Comment by arnaudlevy** [comment]
https://communicationetdemocratie.netlify.app/fr/enjeux/communication-consommation/
Sur le bloc plaidoyers, il ne faut pas les 2 titres, c'est moche.
Je propose : 
- si titre et pas de lien, juste le titre
- si lien et pas de titre, lien affiché avec le titre de l'article
- si lien et titre, on utilise le titre et on lui ajoute le lien de l'article
Dans l'exemple, ça veut dire qu'on aurait "RETROUVEZ NOS PLAIDOYER SUR LES ENJEUX DE COMMUNICATION COMMERCIALE" cliquable, et pas "playdoyers" dessous. C'est trop long, mais ça marche

**Comment by arnaudlevy** [comment]
Par ailleurs dans le même bloc, les cercles doivent faire 2 cols, pas 3 (cf figma)

**Comment by arnaudlevy** [comment]
https://communicationetdemocratie.netlify.app/fr/l-association/agir-et-soutenir/
Il manque le fond jaune

**Comment by arnaudlevy** [comment]
Dans le menu, agir et soutenir n'a pas son rectangle jaune
